# Descriptions are not added as labels are self-explanatory

# Priorities
- name: "priority: critical"
  color: "B60205"
- name: "priority: high"
  color: "D93F0B"
- name: "priority: medium"
  color: "FBCA04"
- name: "priority: low"
  color: "0E8A16"

# Statuses
- name: "status: can't reproduce"
  color: "1D76DB"
- name: "status: duplicate"
  color: "006B75"
- name: "status: identified"
  color: "E99695"
- name: "status: in progress"
  color: "F9D0C4"
- name: "status: missing content"
  color: "0052CC"
- name: "status: resolved"
  color: "FEF2C0"
- name: "status: third party related"
  color: "5319E7"

# Types
- name: "type: bug"
  color: "D4C5F9"
- name: "type: feature request"
  color: "C2E0C6"
